name: Build and Push Docker Image

on:
  # Trigger the workflow on push or pull requests to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true  # Push to Docker Hub
          tags: |
            # Replace 'your-repo-name' with your Docker Hub repository name
            ${{ secrets.DOCKER_USERNAME }}/challenge-1:latest  
            # Add a unique tag based on the Git commit hash
            ${{ secrets.DOCKER_USERNAME }}/challenge-1:${{ github.sha }}  
